
version: 2

models:
- name: stg_orders
  columns:
    - name: order_id
      tests: [unique, not_null]
    - name: amount
      tests: [not_null]
    - name: order_date
      tests:
        - accepted_range:
            max_value: "{{ date_trunc('day', current_date()) }}"
